spring.application.name=module1introduction

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:C:/Users/HARSHITHA/Downloads/module1Introduction/db
spring.datasource.username=harshithaDB
spring.datasource.password=harshitha123

spring.jpa.hibernate.ddl-auto=update
